#!/bin/bash --login
#
#PBS -l select=1:ncpus=36
#PBS -l place=excl
#PBS -N cpu_node_10epochs_178days_old_network
#PBS -A d167
#PBS -l walltime=0:50:0



# Switch to current working directory
cd $PBS_O_WORKDIR

# Run the parallel program
#module load anaconda/python3
#/lustre/home/d167/s1137563/ENTER/condabin/conda activate unet 
#/lustre/home/d167/s1137563/ENTER/bin/python3 main.py
module load miniconda 
/lustre/home/d167/s1137563/ENTER/bin/python3 main.py > output 2> error



