#!/bin/bash --login
#
#PBS -q gpu
#PBS -l select=1:ncpus=40:ngpus=4
#PBS -N 10e_k_5
#PBS -A d167
#PBS -l walltime=1:30:0



# Switch to current working directory
cd $PBS_O_WORKDIR

# Run the parallel program
#module load anaconda/python3
#/lustre/home/d167/s1137563/ENTER/condabin/conda activate unet 
#/lustre/home/d167/s1137563/ENTER/bin/python3 main.py
module load miniconda 
/lustre/home/d167/s1137563/ENTER/bin/python3 main.py > output 2> error



